language: python
python:
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install -r requirements.txt
  - pip install codecov coverage pytest pytest-cov pytest-runner
  - python setup.py install
script:
  - pytest --cov-config .coveragerc --cov=release_exporter -vv
after_success:
  - codecov
