language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codecov nose coverage
  - python setup.py install
script:
  - nosetests --with-coverage
after_success:
  - codecov