trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      addToPath: true
    displayName: Using Python 3.7
  - script: |
      pip install -r requirements.txt
      pip install codecov coverage pytest pytest-cov pytest-runner
    displayName: Installing Python Dependencies
  - script: codecov
    displayName: Uploading Code Coverage